### ISSUE TITLE
Image Download limit?

### ISSUE THREAD

**Issue by bbdbby** [Confuzu/CivitAI-Model-grabber#1]
I just tried this tool for the first time after becoming a huge fan of your image-grabber tool. I notice that it will only download the first 10 sample images even in cases where there might be 20. Is that a limitation of CivitAI API or can that limit be increased to 20? Also curious if there was some crazy way to download each image from the creator relating to a model. For example, some developers may put up 20-40 images showcasing a lora/TI but they will be located in the gallery...could one possibly utilize the user name to download these images but somehow still put them in the correct model folder?

If none of this is possible, I still want to thank for an excellent tool! Really appreciate you putting the work into this and putting it out for people to use. Thanks!

**Comment by bbdbby** [comment]
Turns out I was incorrect. This is actually downloading all of the images. Sorry for the confusion.

**Comment by Confuzu** [comment]
ok then all problems solved.

**Comment by bbdbby** [comment]
This one is interesting. On some models, it is downloading many images beyond 10. Let's say models from JernauGurgeh, it may download as many as 40+ images, so beyond the standard image gallery. But then I'm noticing that with models from h-madoka it's mixed. Some models are downloading more than 10 and others are stopping at 10 even though there are more (usually 20) in the main gallery. Could be something with how people are uploading images or it could be that there are some differences in how the API fetches more images beyond the first 10? No idea, but I thought I would let you know in case you ever revisited this code.
