### ISSUE TITLE
No module named "requests"

### ISSUE THREAD

**Issue by LeonWGal** [Confuzu/CivitAI-Model-grabber#19]
![image](https://github.com/user-attachments/assets/226f8285-a68b-41e5-95e3-9a8b7be17e05)
I have tried the script that I downloaded recently, and the problem persists. Can you please help me solve it?

**Comment by Confuzu** [comment]
yes, you need to  install  requests with  pip install -r requirements.txt

**Comment by LeonWGal** [comment]
Thanks
