### ISSUE TITLE
UnboundLocalError: local variable 'file_name' referenced before assignment

### ISSUE THREAD

**Issue by ElRandom78** [Confuzu/CivitAI-Model-grabber#2]
Hi Confuzu! Thanks in Advance for your Fantastic Tool! It's amazing  :) 
I'm writing to you because yesterday I tried to download files from Civitai, from user nochekaiser881.
The Script has downloaded on the 1° try, a huge amount of files, organizing them in 729 folders, but, unfortunately has not downloaded the complete entirety of the Archive of noche, (his archive count 1473 in total at this moment).

At a certain point, during the download, it has shown this error :
![Unbound Local Error](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/7d6dd63f-c9b8-4325-86fa-b7bed2cbb65c)

Can you fix this please?

**Comment by Confuzu** [comment]
I will look into it

**Comment by Confuzu** [comment]
i updated the code i had no problems anymore with downloading the the specific username nochekaiser881. The difference between the archive an the downloads could be come from here 
# Skip if 'name' or 'downloadUrl' keys are missing

**Comment by ElRandom78** [comment]
ok, thanks for your Replky, Sir. But I have noticed another problem with your script on the same user: nochekaiser881.
In some cases, for several Loras, your script download safetensor files not usable, because it download some file.safetensors of few kylobytes instead of the canonic weight of 36, 72, MB , ecc... I can't understand why.

I post you an example of a Lora not usable, that I downloaded through the script:

![EXAMPLE_LORA_NOT_USABLE](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/5a8a5913-c15e-44d4-9049-2e2c557f63b2)

can you take a look at this?

**Comment by Confuzu** [comment]
i found why some safetensors are only a few kylobytes. CivitAI changed there API so  that creator of Assets have the Option to lock there content behind the civitAI login. 

"The creator of this asset requires you to be logged in to download it" 

I'll see what I can do

**Comment by Confuzu** [comment]
I added Token auth to the script. it should now download all of them, including those hidden behind the login. 
Please open a new Issues if you  found some. 
Thanks

**Comment by ElRandom78** [comment]
OMG, You're Incredible Sir! You have completely solve the problem. With the API KEY TOKEN, the new Script now has successfully downloaded the entire archive. :)  thank you, Have a nice Christmas

**Comment by ElRandom78** [comment]
![no-problem-anime-girl-happy-swaying-53cu4qa1gf3z3b62](https://github.com/Confuzu/CivitAI-Model-grabber/assets/151367269/17255996-92d0-4dbc-be8d-4f27d8120042)
