### ISSUE TITLE
Suggestion/Request - Subfolders under Lora/Checkpoint/etc stating which model type (ex. SD1.5, SDXL, Pony, Flux, etc...)

### ISSUE THREAD

**Issue by jpummill** [Confuzu/CivitAI-Model-grabber#21]
Hi Confuzu, this is a great tool for downloading models and thank you for creating and sharing it.

I would like to suggest that you add an enhancement that subdivides an authors models into subfolders by model type (ex. SD1.5, SDXL, Pony, Flux, etc....)  I believe this information is available in the JSON that is retrieved with each model.

This would be useful because often the model name does not include information about which model type it relates to.

**Comment by Confuzu** [comment]
thanks for the idea, please update and read the updated readme
