### ISSUE TITLE
Suggestion/Request - Download/Save each models webpage for later reference

### ISSUE THREAD

**Issue by jpummill** [Confuzu/CivitAI-Model-grabber#22]
Please consider enhancing the tool to download/save the CivitAI webpage for each model (Checkpoint/Lora/etc...) saved with the model as this page often contains usage instructions that would be lost if the model is ever deleted

**Comment by Confuzu** [comment]
Since my tool only communicates with the API of CivitAI, I cannot download and save the page of the model. 
But what I can try is to save the description of the Item that comes with the API.

**Comment by Confuzu** [comment]
the script now saves the Description to  an HTML  file just double click it to  open it in your favorite  Browser.

**Comment by jpummill** [comment]
This is great.  Thank you!!!

    On Saturday, September 28, 2024 at 03:21:41 PM CDT, Confuzu ***@***.***> wrote:  
 
 


the script now saves the Description to an HTML file just double click it to open it in your favorite Browser.
