### ISSUE TITLE
Request - Organization of Previous and Future Releases by Versions

### ISSUE THREAD

**Issue by ElRandom78** [Confuzu/CivitAI-Model-grabber#5]
Hi Confuzu. 
First of All, Thank you for maintaining updated python code of CivitAI-Model-grabber. 
It's the best tool ever written in python code, - and I can't stop using it :) - for downloading CIVITAI stuffs 👍 🥇 

I write to you for this reason : 

If it's possbile , 
can you re-post previous versions of CIVITAI-model-Grabber please?

It would be TOP if them would be organized by a structured tree, version by version - under "TAGS "  , like this: 
1.0
1.1
1.2, ecc.. 
for every release of the code, also for future releases)

So, yeah, not issue, but a personal request.

**Comment by Confuzu** [comment]
if you  want the old version you  can check  them out on https://github.com/Confuzu/CivitAI-Model-grabber/commits/main/ and click  on the angle brackets <> to  see the old versions

**Comment by ElRandom78** [comment]
Thank you!
