### ISSUE TITLE
Model Downloads [Suggestions + Glitches]

### ISSUE THREAD

**Issue by Worldgate** [Confuzu/CivitAI-Model-grabber#8]
Great program, it's almost everything I been looking for and then some.  However if it was able to put models into category folders, such as say LORA into the LORA directory, Models into MODEL, etc.  Also im not sure how it handles it when someone uploads the same name multiple times, either different versions or different file types, that might be something to look at.  For example, some people have uploaded an fp32 and fp16, same name, but the system gives them different internal names, perhaps that might be a solution.  Anyways thanks for the great program, going to save me hours of work, days even.

**Comment by Worldgate** [comment]
When i said hash before, i meant the short 10 character one thats the first 10 characters of the sha256.  Likewise, found a bug, sometimes it truncates the front of the name of the file if it happens to share the same name as the folder.  Cynfall's 'Blaziken' model for example does this.

**Comment by Worldgate** [comment]
One more before i goto bed, in some instances it doesn't give the models names, i end up with files named .safetensors

**Comment by Confuzu** [comment]
fixed the bug where  the files  have  no names only .file extension 
 also reorganized the Folder Structure

**Comment by Worldgate** [comment]
Thats awesome bro (non gender specific term from the 90s), i'll check it out. :)  I've really been looking for a fire-and-forget method to archive the models i actually like without having to go manually do it.  This tool has been the best so far.

**Comment by Worldgate** [comment]
Just so you know, there is a bug in which if the name of the model (ie the foldername) is the same as the actual file name, it truncates the file.  For example.

ArcanineFRL22nO.safetensors becomes FRL22nO.safetensors inside the folder Arcanine.

This Lora belongs to Cynfall.  The actual model name is "Arcanine" so I am guessing its removing the duplicate name as even the details.txt says the filename is ArcanineFRL22nO.safetensors.

**Comment by Confuzu** [comment]
please try the new update
